# Generated by Django 4.1.9 on 2023-07-27 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roompic', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomInfo',
        ),
    ]
